export * from './lib/gisday-platform-ngx-core.module';
export * from './lib/pages/landing/landing.module';
export * from './lib/pages/events/event.module';
export * from './lib/pages/faq/faq.module';
export * from './lib/pages/sponsors/sponsors.module';
export * from './lib/pages/about/about.module';
export * from './lib/pages/people/people.module';
export * from './lib/pages/competitions/competitions.module';
export * from './lib/pages/account/account.module';
export * from './lib/pages/login/login.module';
export * from './lib/pages/logout/logout.module';
export * from './lib/pages/admin/admin.module';
export * from './lib/pages/contact/contact.module';
export * from './lib/pages/highschool/highschool.module';
export * from './lib/pages/wayback/wayback.module';
export * from './lib/pages/not-authed/not-authed.module';
export * from './lib/pages/not-found/not-found.module';
export * from './lib/pages/callback/callback.module';

