variables:
  EXCLUDED_PROJECTS: 'aggiemap-angular-e2e,correction-lite-angular,correction-lite-angular-e2e,covid-data-api-nest,cpa-angular,cpa-angular-e2e,cpa-nest,geoservices-angular,geoservices-angular-e2e,geoservices-nest,gisday-angular,gisday-angular-e2e,gisday-bridge-nest,gisday-competitions-angular,gisday-competitions-angular-e2e,gisday-competitions-nest,gisday-nest,kissingbug-angular,kissingbug-angular-e2e,mailroom-angular,mailroom-angular-e2e,mailroom-helper-nest,mailroom-nest,oidc-admin-angular,oidc-admin-angular-e2e,oidc-admin-nest,oidc-provider-nest,signage-angular,signage-angular-e2e,trees-angular,trees-angular-e2e,ts-events-angular-e2e,ts-football-angular-e2e,ts-move-in-out-angular-e2e,ts-ring-day-angular-e2e,two-angular,two-angular-e2e,two-dashboard-angular,two-dashboard-angular-e2e,two-data-api-nest,two-directory-nest,two-valup-nest,ues-effluent-angular,ues-effluent-angular-e2e,ues-effluent-data-api-nest,ues-operations-angular,ues-operations-angular-e2e,ues-operations-nest,ues-recycling-angular,ues-recycling-angular-e2e,ues-recycling-data-api-nest,ues-valves-angular,ues-valves-angular-e2e,ues-valves-nest,veoride-data-api-nest,veoride-data-compiler-node,veoride-scraper-node'
  IS_DEVELOPMENT: $[eq(variables['Build.SourceBranchName'], 'development')]
  IS_MASTER: $[eq(variables['Build.SourceBranchName'], 'master')]
  ${{ if and(ne(variables['Build.SourceBranchName'], 'master'), ne(variables['Build.SourceBranchName'], 'development')) }}:
    AFFECTED_BASE: origin/development # Default affected base base
  ${{ if eq(variables['Build.SourceBranchName'], 'development') }}:
    AFFECTED_BASE: origin/development~ # Affected base if build branch name is development
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    AFFECTED_BASE: origin/master~ # Affected base if build branch name is master
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestId) # You can use $(System.PullRequest.PullRequestNumber if your pipeline is triggered by a PR from GitHub ONLY)
    TARGET_BRANCH: $[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(Build.SourceBranchName)
  HEAD_SHA: $(git rev-parse HEAD)

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Setup
    displayName: 'Setup'
    jobs:
      - template: templates/jobs/deltaConfigure.yml

  - stage: Dependencies
    jobs:
      - template: templates/jobs/cacheOrRestoreDependencies.yml

  - stage: Lint
    dependsOn:
      - Setup
      - Dependencies
    variables:
      baseSha: $[stageDependencies.Setup.Last_SHA.outputs['last_successful_sha.BASE_SHA']]
    jobs:
      - template: templates/jobs/lintProjects.yml

  - stage: Build
    dependsOn:
      - Setup
      - Dependencies
    variables:
      baseSha: $[stageDependencies.Setup.Last_SHA.outputs['last_successful_sha.BASE_SHA']]
    jobs:
      - template: templates/jobs/build.yml
        parameters:
          buildType: development
      - template: templates/jobs/build.yml
        parameters:
          buildType: production

  - stage: Tag
    dependsOn:
      - Setup
      - Build
    variables:
      baseSha: $[stageDependencies.Setup.Last_SHA.outputs['last_successful_sha.BASE_SHA']]
    jobs:
      - template: templates/jobs/buildTags.yml
