variables:
  EXCLUDED_PROJECTS: 'kissingbugs-angular,two-dashboard-angular-e2e,aggiemap-angular-e2e,two-data-api-nest,mailroom-angular-e2e,two-directory-nest,correction-lite-angular-e2e,two-valup-nest,covid-data-api-nest,ues-effluent-angular,cpa-angular,oidc-admin-angular,ues-effluent-angular-e2e,cpa-angular-e2e,oidc-admin-angular-e2e,ues-effluent-data-api-nest,cpa-nest,oidc-admin-nest,geoservices-angular,oidc-provider-nest,ues-operations-angular-e2e,geoservices-angular-e2e,signage-angular,geoservices-nest,signage-angular-e2e,ues-recycling-angular,gisday-angular,trees-angular,ues-recycling-angular-e2e,gisday-angular-e2e,trees-angular-e2e,ues-recycling-data-api-nest,gisday-bridge-nest,ues-valves-angular,gisday-competitions-angular,ts-move-in-out-angular-e2e,ues-valves-angular-e2e,gisday-competitions-angular-e2e,ues-valves-nest,gisday-competitions-nest,ts-ring-day-angular-e2e,veoride-data-api-nest,gisday-nest,two-angular,veoride-data-compiler-node,kissingbug-angular,two-angular-e2e,veoride-scraper-node,kissingbug-angular-e2e,two-dashboard-angular'
  IS_DEVELOPMENT: $[eq(variables['Build.SourceBranchName'], 'development')]
  IS_MASTER: $[eq(variables['Build.SourceBranchName'], 'master')]
  ${{ if and(ne(variables['Build.SourceBranchName'], 'master'), ne(variables['Build.SourceBranchName'], 'development')) }}:
    AFFECTED_BASE: origin/development # Default affected base base
  ${{ if eq(variables['Build.SourceBranchName'], 'development') }}:
    AFFECTED_BASE: origin/development~ # Affected base if build branch name is development
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    AFFECTED_BASE: origin/master~ # Affected base if build branch name is master
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestId) # You can use $(System.PullRequest.PullRequestNumber if your pipeline is triggered by a PR from GitHub ONLY)
    TARGET_BRANCH: $[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(Build.SourceBranchName)
  HEAD_SHA: $(git rev-parse HEAD)

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Setup
    displayName: 'Setup'
    jobs:
      - template: templates/jobs/deltaConfigure.yml

  - stage: Dependencies
    jobs:
      - template: templates/jobs/cacheOrRestoreDependencies.yml

  - stage: Lint
    dependsOn:
      - Setup
      - Dependencies
    variables:
      baseSha: $[stageDependencies.Setup.Last_SHA.outputs['last_successful_sha.BASE_SHA']]
    jobs:
      - template: templates/jobs/lintProjects.yml

  - stage: Build
    dependsOn:
      - Setup
      - Dependencies
    variables:
      baseSha: $[stageDependencies.Setup.Last_SHA.outputs['last_successful_sha.BASE_SHA']]
    jobs:
      - template: templates/jobs/build.yml
        parameters:
          buildType: development
      - template: templates/jobs/build.yml
        parameters:
          buildType: production

  - stage: Tag
    dependsOn:
      - Setup
      - Build
    variables:
      baseSha: $[stageDependencies.Setup.Last_SHA.outputs['last_successful_sha.BASE_SHA']]
    jobs:
      - template: templates/jobs/buildTags.yml
