# This is a sample docker-compose.yml file for the gisday-nest API
# Can be combined with the docker-compose.dev.yml + the docker-compose for the front-end for a full stack in production

version: '3'

name: gisday
services:
  api:
    build: . # Path is assumed inside the /dist/apps/<app-name> folder
    image: ghcr.io/tamugeoinnovation/geoservices-nest:latest
    container_name: api
    ports:
      - '3333:3333'
    environment:
      - GLOBAL_PREFIX=${GLOBAL_PREFIX}
      - ORIGINS=${ORIGINS}
      - MAILROOM_URL=${MAILROOM_URL}
      - MAILROOM_FROM=${MAILROOM_FROM}
    restart: always

volumes:
  data:
