import { Component, OnDestroy, ChangeDetectionStrategy, inject } from '@angular/core';
import { PopupComponent } from '../base/base.component';

import { EsriMapService } from '@tamu-gisc/maps/esri';
import { PopupService } from '../../services/popup.service';
import { DragService } from '@tamu-gisc/ui-kits/ngx/interactions/draggable';

import { NgClass, AsyncPipe } from '@angular/common';

import { DragDirective } from '@tamu-gisc/ui-kits/ngx/interactions/draggable';
import { RenderHostDirective } from '@tamu-gisc/ui-kits/ngx/layout';

@Component({
  selector: 'tamu-gisc-feature-mobile-popup',
  templateUrl: './mobile.component.html',
  styleUrls: ['./mobile.component.scss'],
  providers: [PopupService],
  changeDetection: ChangeDetectionStrategy.Eager,
  imports: [DragDirective, NgClass, RenderHostDirective, AsyncPipe]
})
export class PopupMobileComponent extends PopupComponent implements OnDestroy {
  private ms: EsriMapService;
  private ps: PopupService;
  private dragService = inject(DragService);

  /**
   * Guid string identifier generated by the DragService and passed into the draggable directive by attribute input.
   *
   * This allows the service and directive to update the drag state which can be accessed by the parent component.
   */
  public identifier: string;

  constructor() {
    const ms = inject(EsriMapService);
    const ps = inject(PopupService);

    super(ms, ps);
    this.ms = ms;
    this.ps = ps;
    const dragService = this.dragService;


    this.identifier = dragService.register(this);
  }

  public ngOnDestroy() {
    // Call base class on destroy method
    super.ngOnDestroy();

    // Perform sub-class-specific on destroy logic
    this.dragService.unregister(this.identifier);
  }
}
