version: '3'

services:
  web:
    build: . # Path is assumed inside the /dist/apps/<app-name> folder
    image: ghcr.io/tamugeoinnovation/mailroom-angular:latest
    container_name: site
    ports:
      - '4200:80'
    environment:
      - API_URL=${ANGULAR_API_URL}
      - G_TAG=${G_TAG}
    restart: always
