export enum CATEGORY {
  WEBSITES = 1,
  PHONE_NUMBERS = 2,
  SITE_OWNERS = 3,
  SITE_SERVICES = 4,
  SITE_RESTRICTIONS = 5,
  SITE_OPERATIONAL_STATUS = 6
}

export enum STATUS {
  PROCESSING = 1,
  CLOSED = 2,
  FLAGGED = 3,
  CANCELLED = 4
}