jobs:
  - job: Tag
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.18'
        displayName: 'Install Node.js'

      - script: npm install
        displayName: 'npm install'

      - bash: |
          npm run nx affected:apps -- --base=$(affectedBase) --head=HEAD --exclude="aggiemap-angular,signage-angular,trees-angular,bikeshare,gisday-competitions-angular,oidc-admin-angular,two-dashboard-angular,two-data-api-nest,two-angular,geoservices-angular,covid-data-api-nest,oidc-provider-express,oidc-provider-nest,oidc-admin-nest,oidc-client-test,oidc-provider-angular,two-valup-nest,two-directory-nest,gisday-angular,gisday-nest,common-ngx-ui-notification,common-ngx-local-store,common-ngx-settings,common-ngx-pipes" | grep -E '( - )(\w|-|\d|_)+' | sed -E 's/ - /##vso[build.addbuildtag]/g'
        displayName: 'add affected apps as buildtags'
