jobs:
  - job:
    displayName: Add Build Tags
    steps:
      - template: ../tasks/cacheOrRestoreDependencies.yml
      - bash: |
          npx nx affected:apps --base=$(baseSha) --head=$(HEAD_SHA) --exclude=$(EXCLUDED_PROJECTS) | grep -E '( - )(\w|-|\d|_)+' | sed -E 's/ - /##vso[build.addbuildtag]/g'
        displayName: 'Add Build Tags for Affected Projects'
