parameters:
  buildType: ''
  dependsOn: []
  excludedProjects: ''

jobs:
  - job: ${{ parameters.buildType }}
    dependsOn: ${{ parameters.dependsOn }}
    steps:
      - template: ../tasks/cacheOrRestoreDependencies.yml

      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'app_configs.zip'
        displayName: 'Download application configuration files'

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: $(Agent.TempDirectory)/app_configs.zip
          cleanDestinationFolder: false
          destinationFolder: $(Agent.TempDirectory)
        displayName: 'Extracting'

      - task: CopyFiles@2
        inputs:
          SourceFolder: $(Agent.TempDirectory)/app_configs
          Contents: '**'
          TargetFolder: $(System.DefaultWorkingDirectory)
        displayName: 'Copy secrets'

      - bash: |
          npm run nx affected:build -- --base=$(affectedBase) --head=HEAD --configuration=${{ parameters.buildType }} --exclude=${{ parameters.excludedProjects }}
        displayName: 'Running build'

      - task: CopyFiles@2
        inputs:
          Contents: 'dist/**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy Distribution Files'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory) # dist or build files
          artifactName: 'js-monorepo-${{ parameters.buildType }}'
        displayName: 'Publish Artifacts'
