jobs:
  - job: Last_SHA
    displayName: 'Last SHA'
    steps:
      # Set Azure Devops CLI default settings
      - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
        displayName: 'Set default Azure DevOps organization and project'

      # Get last successful commit from Azure Devops CLI
      - bash: |
          LAST_SHA=$(az pipelines build list --branch $(Build.SourceBranchName) --definition-ids $(System.DefinitionId) --result succeeded --top 1 --query "[0].sourceVersion")

          # Check if the last sha is not empty OR if the last sha is not a commit in the repo (as would be the case in the event of a rebase)
          if [ -z "$LAST_SHA" ]; then
            echo "Last successful commit SHA is empty. Using fallback affected base."
            LAST_SHA=$(AFFECTED_BASE)
          elif [ "$(git cat-file -t $LAST_SHA)" != "commit" ]; then
            echo "Last successful commit SHA ($LAST_SHA) is not a commit in the repo. Using fallback affected base."
            LAST_SHA=$(AFFECTED_BASE)
          fi

          echo "Last successful commit SHA: $LAST_SHA"
          echo "##vso[task.setvariable variable=BASE_SHA;isOutput=true]$LAST_SHA"
        displayName: 'Get last successful commit SHA'
        name: 'last_successful_sha'
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
