parameters:
  excludedProjects: ''

jobs:
  - job: Last_SHA
    displayName: 'Last SHA'
    steps:
      # Set Azure Devops CLI default settings
      - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
        displayName: 'Set default Azure DevOps organization and project'

      # Get last successful commit from Azure Devops CLI
      - bash: |
          LAST_SHA=$(az pipelines build list --branch $(Build.SourceBranchName) --definition-ids $(System.DefinitionId) --result succeeded --top 1 --query "[0].sourceVersion")
          if [ -z $LAST_SHA ]
          then
            LAST_SHA=$(AFFECTED_BASE)
          fi
          echo "Last successful commit SHA: $LAST_SHA"
          echo "##vso[task.setvariable variable=BASE_SHA;isOutput=true]$LAST_SHA"
        displayName: 'Get last successful commit SHA'
        name: 'last_successful_sha'
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
