parameters:
  excludedProjects: ''
jobs:
  - job:
    displayName: Lint Affected
    steps:
      - checkout: self
        fetchDepth: 99
      - template: ../tasks/cacheOrRestoreDependencies.yml
      - bash: |
          git fetch --all
          npm run nx affected:lint -- --base=$(baseSha) --head=$(HEAD_SHA)
        displayName: 'Lint '
