parameters:
  excludedProjects: ''

jobs:
  - job:
    displayName: Lint Affected
    steps:
      - template: ../tasks/cacheOrRestoreDependencies.yml
      - bash: |
          npm run nx affected:lint -- --base=$(affectedBase) --head=HEAD
        displayName: 'Lint '
