parameters:
  excludedProjects: ''

jobs:
  - job:
    displayName: Lint Affected
    steps:
      - template: ../tasks/cacheOrRestoreDependencies.yml
      - bash: |
          npm run nx affected:lint -- --base=$(BASE_SHA) --head=$(HEAD_SHA)
        displayName: 'Lint '
