jobs:
  - job:
    displayName: Lint Affected
    steps:
      - template: ../tasks/cacheOrRestoreDependencies.yml
      - bash: |
          npx nx affected:lint --configuration=production --base=$(baseSha)  --exclude=$(EXCLUDED_PROJECTS) --parallel=2
        displayName: 'Lint Affected'
