steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.23.3'
    displayName: 'Install Node.js 22.23.3'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | $(System.DefaultWorkingDirectory)/package.json | $(System.DefaultWorkingDirectory)/package-lock.json | $(System.DefaultWorkingDirectory)/templates/tasks/cacheOrRestoreDependencies.yml | $(System.DefaultWorkingDirectory)/azure-pipelines.yml'
      path: '$(System.DefaultWorkingDirectory)/node_modules'
      cacheHitVar: 'CacheHit'

  - script: npm ci
    displayName: 'NPM Clean Dependency Install'
    condition: ne(variables.CacheHit, 'true')
