# This is a sample docker-compose.yml file for the gisday-nest API
# Can be combined with the docker-compose.dev.yml + the docker-compose for the front-end for a full stack in production

version: '3'

name: gisday
services:
  api:
    image: gisday-nest:latest
    ports:
      - '3333:3333'
    environment:
      - PORT=${PORT}
      - GLOBAL_PREFIX=${GLOBAL_PREFIX}
      - ORIGINS=${ORIGINS}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ISSUER_URL=${AUTH0_ISSUER_URL}
      - AUTH0_MANAGEMENT_DOMAIN=${AUTH0_MANAGEMENT_DOMAIN}
      - AUTH0_MANAGEMENT_CLIENT=${AUTH0_MANAGEMENT_CLIENT}
      - AUTH0_MANAGEMENT_SECRET=${AUTH0_MANAGEMENT_SECRET}
      - APP_DATA=${APP_DATA}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}
      - TYPEORM_DROP_SCHEMA=${TYPEORM_DROP_SCHEMA}
      - TYPEORM_LOGGING=${TYPEORM_LOGGING}
      - TYPEORM_DRIVER_EXTRA=${TYPEORM_DRIVER_EXTRA}
      - MAILROOM_URL=${MAILROOM_URL}
      - MAILROOM_FROM=${MAILROOM_FROM}
      - MAILROOM_TO=${MAILROOM_TO}
      - MAILROOM_BCC=${MAILROOM_BCC}
    restart: always
