version: '3'

name: gisday
services:
  api:
    image: gisday-nest:latest
    ports:
      - '3333:3333'
    environment:
      - PORT=${PORT}
      - GLOBAL_PREFIX=${GLOBAL_PREFIX}
      - ORIGINS=${ORIGINS}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ISSUER_URL=${AUTH0_ISSUER_URL}
      - APP_DATA=${APP_DATA}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}
      - TYPEORM_DROP_SCHEMA=${TYPEORM_DROP_SCHEMA}
      - TYPEORM_LOGGING=${TYPEORM_LOGGING}
      - TYPEORM_DRIVER_EXTRA=${TYPEORM_DRIVER_EXTRA}
    restart: always
