version: '3.8'

services:
  web:
    build: . # Path is assumed inside the /dist/apps/<app-name> folder
    image: ghcr.io/tamugeoinnovation/gisday-angular:latest
    container_name: site
    ports:
      - '4200:80'
    environment:
      - ANGULAR_API_URL=${ANGULAR_API_URL}
      - ANGULAR_AUTH0_URLS=${ANGULAR_AUTH0_URLS}
      - ANGULAR_AUTH0_DOMAIN=${ANGULAR_AUTH0_DOMAIN}
      - ANGULAR_AUTH0_CLIENT_ID=${ANGULAR_AUTH0_CLIENT_ID}
      - ANGULAR_AUTH0_AUDIENCE=${ANGULAR_AUTH0_AUDIENCE}
      - ANGULAR_AUTH0_ROLES_CLAIM=${ANGULAR_AUTH0_ROLES_CLAIM}
      - G_TAG=${G_TAG}
    restart: always
