describe('Routing', () => {
  before(() => {
    cy.visit('https://aggiemap.tamu.edu/map/d/trip')
  })
  it('Check Sidebar Closes - Directions Toggle', () => {
    cy.get('.tabs > :nth-child(2) > .esri-component')
      .should('be.visible')
      .click({force: true})
      .click({force: true})
    cy.get('tamu-gisc-sidebar')
      .should('not.be.visible')
  })
  it('Check Sidebar Opens - Directions Toggle', () => {
    cy.get('.tabs > :nth-child(2) > .esri-component')
    .should('be.visible')
    .click({force: true})
    cy.get('tamu-gisc-sidebar')
      .should('be.visible')
  })
  it('Title Logo', () => {
    cy.get('tamu-gisc-tamu-block > img')
      .should('have.attr', 'alt', 'Texas A&M University Logo')
      .and('have.attr', 'src', 'assets/images/logo/TAM-PrimaryMarkBB.svg')
  })
  it('Input1', () => {
    cy.get(':nth-child(1) > :nth-child(1) > .input-action-container > .margin-right')
      .should('have.attr', 'role', 'textbox')
      .and('have.attr', 'placeholder', 'Choose point or click on the map')
      .as('input1')
      .click()
    cy.get('.focusable')
      .click()
    cy.get('[style=""] > :nth-child(1) > .input-action-container > .margin-right')
      .should('have.value', 'Trigon (Default')
    cy.contains('.title', 'Geolocation failed')
    cy.contains('.description', 'please ensure Aggie Map is allowed to use your location.')
  })
  it('Input2', () => {
    cy.get(':nth-child(2) > :nth-child(1) > .input-action-container > .margin-right')
      .should('have.attr', 'role', 'textbox')
      .and('have.attr', 'placeholder', 'Choose point or click on the map')
      .as('input2')
      .click()
    cy.get('.focusable')
      .click()
    cy.get(':nth-child(2) > :nth-child(1) > .input-action-container > .margin-right')
      .should('have.value', 'Trigon (Default')
    cy.contains('.title', 'Geolocation failed')
    cy.contains('.description', 'please ensure Aggie Map is allowed to use your location.')
  })
  it('Options', () => {
    cy.contains('.action', 'Options')
      .click()
    cy.url()
      .should('contain', 'options')
    cy.get('#options-return')
      .click()
  })
})