/// <reference path="../support/index.d.ts" />
describe('Routing', () => {
  before(() => {
    cy.server()
    cy.checkMapApi('**/TAMU_BaseMap/**', 'GET', 'basemap')
    cy.visit('https://aggiemap.tamu.edu/map/d/trip')
    cy.wait('@basemap')
    cy.get('canvas')
      .should('be.visible', {timeout: 5000})
    cy.server({enable: false})
  })
  
  it('Check Sidebar Closes - Directions Toggle', () => {
    cy.getDirectionsToggle()
      .click({force: true})
      .click({force: true})
    cy.getSideBar('not.be.visible')
  })
  it('Check Sidebar Opens - Directions Toggle', () => {
    cy.getDirectionsToggle()
      .click({force: true})
    cy.getSideBar('be.visible')
  })
  it('Title Logo', () => {
    cy.checkTitleLogo()
  })
  it('Input1', () => {
    cy.getDirectionsInput('1')
      .click()
    cy.get('.focusable')
      .click()
    cy.get(':nth-child(1) > :nth-child(1) > .input-action-container > .margin-right')
      .should('have.value', 'Trigon (Default')
    cy.contains('.title', 'Geolocation failed')
    cy.contains('.description', 'please ensure Aggie Map is allowed to use your location.')
  })
  it('Input2', () => {
    cy.getDirectionsInput('2')
      .click()
    cy.get('.focusable')
      .click()
    cy.get(':nth-child(2) > :nth-child(1) > .input-action-container > .margin-right')
      .should('have.value', 'Trigon (Default)')
    cy.contains('.title', 'Geolocation failed')
    cy.contains('.description', 'please ensure Aggie Map is allowed to use your location.')
  })
  it('Options', () => {
    cy.contains('.action', 'Options')
      .click()
    cy.url()
      .should('contain', 'options')
    cy.get('#options-return')
      .click()
  })
})