name: Build Affected

on:
  workflow_call:

env:
  EXCLUDED_PROJECTS: 'aggiemap-angular-e2e,covid-data-api-nest,cpa-angular,cpa-angular-e2e,cpa-nest,geoservices-angular-e2e,gisday-bridge-nest,gisday-competitions-angular,gisday-competitions-angular-e2e,gisday-competitions-nest,kissingbug-angular,kissingbug-angular-e2e,mailroom-angular-e2e,oidc-admin-angular,oidc-admin-angular-e2e,oidc-admin-nest,oidc-provider-nest,signage-angular,signage-angular-e2e,trees-angular,trees-angular-e2e,two-angular,two-angular-e2e,two-dashboard-angular,two-dashboard-angular-e2e,two-data-api-nest,two-directory-nest,two-valup-nest,ues-effluent-angular,ues-effluent-angular-e2e,ues-effluent-data-api-nest,ues-operations-angular,ues-operations-angular-e2e,ues-operations-nest,ues-recycling-angular,ues-recycling-angular-e2e,ues-recycling-data-api-nest,ues-valves-angular,ues-valves-angular-e2e,ues-valves-nest,veoride-data-api-nest,veoride-data-compiler-node,veoride-scraper-node'

jobs:
  build:
    name: Affected
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.17.0'

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Affected
        run: npx nx affected:build --configuration=production --exclude=${{ env.EXCLUDED_PROJECTS }}  --base=origin/development --parallel=2

      - name: Copy Files Needed For Image Build
        run: |
          mkdir -p dist
          cp -r package.json package-lock.json scripts/ci/tokenSubstitute.sh dist/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: dist/
          include-hidden-files: true
